import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ResourceSearchHitOrderByWithRelationInputObjectSchema as ResourceSearchHitOrderByWithRelationInputObjectSchema } from './objects/ResourceSearchHitOrderByWithRelationInput.schema';
import { ResourceSearchHitWhereInputObjectSchema as ResourceSearchHitWhereInputObjectSchema } from './objects/ResourceSearchHitWhereInput.schema';
import { ResourceSearchHitWhereUniqueInputObjectSchema as ResourceSearchHitWhereUniqueInputObjectSchema } from './objects/ResourceSearchHitWhereUniqueInput.schema';
import { ResourceSearchHitCountAggregateInputObjectSchema as ResourceSearchHitCountAggregateInputObjectSchema } from './objects/ResourceSearchHitCountAggregateInput.schema';
import { ResourceSearchHitMinAggregateInputObjectSchema as ResourceSearchHitMinAggregateInputObjectSchema } from './objects/ResourceSearchHitMinAggregateInput.schema';
import { ResourceSearchHitMaxAggregateInputObjectSchema as ResourceSearchHitMaxAggregateInputObjectSchema } from './objects/ResourceSearchHitMaxAggregateInput.schema';

export const ResourceSearchHitAggregateSchema: z.ZodType<Prisma.ResourceSearchHitAggregateArgs> = z.object({ orderBy: z.union([ResourceSearchHitOrderByWithRelationInputObjectSchema, ResourceSearchHitOrderByWithRelationInputObjectSchema.array()]).optional(), where: ResourceSearchHitWhereInputObjectSchema.optional(), cursor: ResourceSearchHitWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ResourceSearchHitCountAggregateInputObjectSchema ]).optional(), _min: ResourceSearchHitMinAggregateInputObjectSchema.optional(), _max: ResourceSearchHitMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ResourceSearchHitAggregateArgs>;

export const ResourceSearchHitAggregateZodSchema = z.object({ orderBy: z.union([ResourceSearchHitOrderByWithRelationInputObjectSchema, ResourceSearchHitOrderByWithRelationInputObjectSchema.array()]).optional(), where: ResourceSearchHitWhereInputObjectSchema.optional(), cursor: ResourceSearchHitWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ResourceSearchHitCountAggregateInputObjectSchema ]).optional(), _min: ResourceSearchHitMinAggregateInputObjectSchema.optional(), _max: ResourceSearchHitMaxAggregateInputObjectSchema.optional() }).strict();