import type { Prisma } from '../../../generated/prisma/client';
import * as z from 'zod';
import { ContactRequestOrderByWithRelationInputObjectSchema as ContactRequestOrderByWithRelationInputObjectSchema } from './objects/ContactRequestOrderByWithRelationInput.schema';
import { ContactRequestWhereInputObjectSchema as ContactRequestWhereInputObjectSchema } from './objects/ContactRequestWhereInput.schema';
import { ContactRequestWhereUniqueInputObjectSchema as ContactRequestWhereUniqueInputObjectSchema } from './objects/ContactRequestWhereUniqueInput.schema';
import { ContactRequestCountAggregateInputObjectSchema as ContactRequestCountAggregateInputObjectSchema } from './objects/ContactRequestCountAggregateInput.schema';
import { ContactRequestMinAggregateInputObjectSchema as ContactRequestMinAggregateInputObjectSchema } from './objects/ContactRequestMinAggregateInput.schema';
import { ContactRequestMaxAggregateInputObjectSchema as ContactRequestMaxAggregateInputObjectSchema } from './objects/ContactRequestMaxAggregateInput.schema';

export const ContactRequestAggregateSchema: z.ZodType<Prisma.ContactRequestAggregateArgs> = z.object({ orderBy: z.union([ContactRequestOrderByWithRelationInputObjectSchema, ContactRequestOrderByWithRelationInputObjectSchema.array()]).optional(), where: ContactRequestWhereInputObjectSchema.optional(), cursor: ContactRequestWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ContactRequestCountAggregateInputObjectSchema ]).optional(), _min: ContactRequestMinAggregateInputObjectSchema.optional(), _max: ContactRequestMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ContactRequestAggregateArgs>;

export const ContactRequestAggregateZodSchema = z.object({ orderBy: z.union([ContactRequestOrderByWithRelationInputObjectSchema, ContactRequestOrderByWithRelationInputObjectSchema.array()]).optional(), where: ContactRequestWhereInputObjectSchema.optional(), cursor: ContactRequestWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ContactRequestCountAggregateInputObjectSchema ]).optional(), _min: ContactRequestMinAggregateInputObjectSchema.optional(), _max: ContactRequestMaxAggregateInputObjectSchema.optional() }).strict();