import type { Prisma } from '../../../generated/prisma/client';
import * as z from 'zod';
import { OpportunityApplicationOrderByWithRelationInputObjectSchema as OpportunityApplicationOrderByWithRelationInputObjectSchema } from './objects/OpportunityApplicationOrderByWithRelationInput.schema';
import { OpportunityApplicationWhereInputObjectSchema as OpportunityApplicationWhereInputObjectSchema } from './objects/OpportunityApplicationWhereInput.schema';
import { OpportunityApplicationWhereUniqueInputObjectSchema as OpportunityApplicationWhereUniqueInputObjectSchema } from './objects/OpportunityApplicationWhereUniqueInput.schema';
import { OpportunityApplicationCountAggregateInputObjectSchema as OpportunityApplicationCountAggregateInputObjectSchema } from './objects/OpportunityApplicationCountAggregateInput.schema';
import { OpportunityApplicationMinAggregateInputObjectSchema as OpportunityApplicationMinAggregateInputObjectSchema } from './objects/OpportunityApplicationMinAggregateInput.schema';
import { OpportunityApplicationMaxAggregateInputObjectSchema as OpportunityApplicationMaxAggregateInputObjectSchema } from './objects/OpportunityApplicationMaxAggregateInput.schema';

export const OpportunityApplicationAggregateSchema: z.ZodType<Prisma.OpportunityApplicationAggregateArgs> = z.object({ orderBy: z.union([OpportunityApplicationOrderByWithRelationInputObjectSchema, OpportunityApplicationOrderByWithRelationInputObjectSchema.array()]).optional(), where: OpportunityApplicationWhereInputObjectSchema.optional(), cursor: OpportunityApplicationWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), OpportunityApplicationCountAggregateInputObjectSchema ]).optional(), _min: OpportunityApplicationMinAggregateInputObjectSchema.optional(), _max: OpportunityApplicationMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.OpportunityApplicationAggregateArgs>;

export const OpportunityApplicationAggregateZodSchema = z.object({ orderBy: z.union([OpportunityApplicationOrderByWithRelationInputObjectSchema, OpportunityApplicationOrderByWithRelationInputObjectSchema.array()]).optional(), where: OpportunityApplicationWhereInputObjectSchema.optional(), cursor: OpportunityApplicationWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), OpportunityApplicationCountAggregateInputObjectSchema ]).optional(), _min: OpportunityApplicationMinAggregateInputObjectSchema.optional(), _max: OpportunityApplicationMaxAggregateInputObjectSchema.optional() }).strict();