import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ScannableDocumentMealHitOrderByWithRelationInputObjectSchema as ScannableDocumentMealHitOrderByWithRelationInputObjectSchema } from './objects/ScannableDocumentMealHitOrderByWithRelationInput.schema';
import { ScannableDocumentMealHitWhereInputObjectSchema as ScannableDocumentMealHitWhereInputObjectSchema } from './objects/ScannableDocumentMealHitWhereInput.schema';
import { ScannableDocumentMealHitWhereUniqueInputObjectSchema as ScannableDocumentMealHitWhereUniqueInputObjectSchema } from './objects/ScannableDocumentMealHitWhereUniqueInput.schema';
import { ScannableDocumentMealHitCountAggregateInputObjectSchema as ScannableDocumentMealHitCountAggregateInputObjectSchema } from './objects/ScannableDocumentMealHitCountAggregateInput.schema';
import { ScannableDocumentMealHitMinAggregateInputObjectSchema as ScannableDocumentMealHitMinAggregateInputObjectSchema } from './objects/ScannableDocumentMealHitMinAggregateInput.schema';
import { ScannableDocumentMealHitMaxAggregateInputObjectSchema as ScannableDocumentMealHitMaxAggregateInputObjectSchema } from './objects/ScannableDocumentMealHitMaxAggregateInput.schema';

export const ScannableDocumentMealHitAggregateSchema: z.ZodType<Prisma.ScannableDocumentMealHitAggregateArgs> = z.object({ orderBy: z.union([ScannableDocumentMealHitOrderByWithRelationInputObjectSchema, ScannableDocumentMealHitOrderByWithRelationInputObjectSchema.array()]).optional(), where: ScannableDocumentMealHitWhereInputObjectSchema.optional(), cursor: ScannableDocumentMealHitWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ScannableDocumentMealHitCountAggregateInputObjectSchema ]).optional(), _min: ScannableDocumentMealHitMinAggregateInputObjectSchema.optional(), _max: ScannableDocumentMealHitMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ScannableDocumentMealHitAggregateArgs>;

export const ScannableDocumentMealHitAggregateZodSchema = z.object({ orderBy: z.union([ScannableDocumentMealHitOrderByWithRelationInputObjectSchema, ScannableDocumentMealHitOrderByWithRelationInputObjectSchema.array()]).optional(), where: ScannableDocumentMealHitWhereInputObjectSchema.optional(), cursor: ScannableDocumentMealHitWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ScannableDocumentMealHitCountAggregateInputObjectSchema ]).optional(), _min: ScannableDocumentMealHitMinAggregateInputObjectSchema.optional(), _max: ScannableDocumentMealHitMaxAggregateInputObjectSchema.optional() }).strict();