import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { MealOccurrenceSearchOrderByWithRelationInputObjectSchema as MealOccurrenceSearchOrderByWithRelationInputObjectSchema } from './objects/MealOccurrenceSearchOrderByWithRelationInput.schema';
import { MealOccurrenceSearchWhereInputObjectSchema as MealOccurrenceSearchWhereInputObjectSchema } from './objects/MealOccurrenceSearchWhereInput.schema';
import { MealOccurrenceSearchWhereUniqueInputObjectSchema as MealOccurrenceSearchWhereUniqueInputObjectSchema } from './objects/MealOccurrenceSearchWhereUniqueInput.schema';
import { MealOccurrenceSearchCountAggregateInputObjectSchema as MealOccurrenceSearchCountAggregateInputObjectSchema } from './objects/MealOccurrenceSearchCountAggregateInput.schema';
import { MealOccurrenceSearchMinAggregateInputObjectSchema as MealOccurrenceSearchMinAggregateInputObjectSchema } from './objects/MealOccurrenceSearchMinAggregateInput.schema';
import { MealOccurrenceSearchMaxAggregateInputObjectSchema as MealOccurrenceSearchMaxAggregateInputObjectSchema } from './objects/MealOccurrenceSearchMaxAggregateInput.schema';
import { MealOccurrenceSearchAvgAggregateInputObjectSchema as MealOccurrenceSearchAvgAggregateInputObjectSchema } from './objects/MealOccurrenceSearchAvgAggregateInput.schema';
import { MealOccurrenceSearchSumAggregateInputObjectSchema as MealOccurrenceSearchSumAggregateInputObjectSchema } from './objects/MealOccurrenceSearchSumAggregateInput.schema';

export const MealOccurrenceSearchAggregateSchema: z.ZodType<Prisma.MealOccurrenceSearchAggregateArgs> = z.object({ orderBy: z.union([MealOccurrenceSearchOrderByWithRelationInputObjectSchema, MealOccurrenceSearchOrderByWithRelationInputObjectSchema.array()]).optional(), where: MealOccurrenceSearchWhereInputObjectSchema.optional(), cursor: MealOccurrenceSearchWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), MealOccurrenceSearchCountAggregateInputObjectSchema ]).optional(), _min: MealOccurrenceSearchMinAggregateInputObjectSchema.optional(), _max: MealOccurrenceSearchMaxAggregateInputObjectSchema.optional(), _avg: MealOccurrenceSearchAvgAggregateInputObjectSchema.optional(), _sum: MealOccurrenceSearchSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.MealOccurrenceSearchAggregateArgs>;

export const MealOccurrenceSearchAggregateZodSchema = z.object({ orderBy: z.union([MealOccurrenceSearchOrderByWithRelationInputObjectSchema, MealOccurrenceSearchOrderByWithRelationInputObjectSchema.array()]).optional(), where: MealOccurrenceSearchWhereInputObjectSchema.optional(), cursor: MealOccurrenceSearchWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), MealOccurrenceSearchCountAggregateInputObjectSchema ]).optional(), _min: MealOccurrenceSearchMinAggregateInputObjectSchema.optional(), _max: MealOccurrenceSearchMaxAggregateInputObjectSchema.optional(), _avg: MealOccurrenceSearchAvgAggregateInputObjectSchema.optional(), _sum: MealOccurrenceSearchSumAggregateInputObjectSchema.optional() }).strict();