import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { PlatformUsageStatsOrderByWithRelationInputObjectSchema as PlatformUsageStatsOrderByWithRelationInputObjectSchema } from './objects/PlatformUsageStatsOrderByWithRelationInput.schema';
import { PlatformUsageStatsWhereInputObjectSchema as PlatformUsageStatsWhereInputObjectSchema } from './objects/PlatformUsageStatsWhereInput.schema';
import { PlatformUsageStatsWhereUniqueInputObjectSchema as PlatformUsageStatsWhereUniqueInputObjectSchema } from './objects/PlatformUsageStatsWhereUniqueInput.schema';
import { PlatformUsageStatsCountAggregateInputObjectSchema as PlatformUsageStatsCountAggregateInputObjectSchema } from './objects/PlatformUsageStatsCountAggregateInput.schema';
import { PlatformUsageStatsMinAggregateInputObjectSchema as PlatformUsageStatsMinAggregateInputObjectSchema } from './objects/PlatformUsageStatsMinAggregateInput.schema';
import { PlatformUsageStatsMaxAggregateInputObjectSchema as PlatformUsageStatsMaxAggregateInputObjectSchema } from './objects/PlatformUsageStatsMaxAggregateInput.schema';
import { PlatformUsageStatsAvgAggregateInputObjectSchema as PlatformUsageStatsAvgAggregateInputObjectSchema } from './objects/PlatformUsageStatsAvgAggregateInput.schema';
import { PlatformUsageStatsSumAggregateInputObjectSchema as PlatformUsageStatsSumAggregateInputObjectSchema } from './objects/PlatformUsageStatsSumAggregateInput.schema';

export const PlatformUsageStatsAggregateSchema: z.ZodType<Prisma.PlatformUsageStatsAggregateArgs> = z.object({ orderBy: z.union([PlatformUsageStatsOrderByWithRelationInputObjectSchema, PlatformUsageStatsOrderByWithRelationInputObjectSchema.array()]).optional(), where: PlatformUsageStatsWhereInputObjectSchema.optional(), cursor: PlatformUsageStatsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), PlatformUsageStatsCountAggregateInputObjectSchema ]).optional(), _min: PlatformUsageStatsMinAggregateInputObjectSchema.optional(), _max: PlatformUsageStatsMaxAggregateInputObjectSchema.optional(), _avg: PlatformUsageStatsAvgAggregateInputObjectSchema.optional(), _sum: PlatformUsageStatsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.PlatformUsageStatsAggregateArgs>;

export const PlatformUsageStatsAggregateZodSchema = z.object({ orderBy: z.union([PlatformUsageStatsOrderByWithRelationInputObjectSchema, PlatformUsageStatsOrderByWithRelationInputObjectSchema.array()]).optional(), where: PlatformUsageStatsWhereInputObjectSchema.optional(), cursor: PlatformUsageStatsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), PlatformUsageStatsCountAggregateInputObjectSchema ]).optional(), _min: PlatformUsageStatsMinAggregateInputObjectSchema.optional(), _max: PlatformUsageStatsMaxAggregateInputObjectSchema.optional(), _avg: PlatformUsageStatsAvgAggregateInputObjectSchema.optional(), _sum: PlatformUsageStatsSumAggregateInputObjectSchema.optional() }).strict();