import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ResourceOccurrenceSearchOrderByWithRelationInputObjectSchema as ResourceOccurrenceSearchOrderByWithRelationInputObjectSchema } from './objects/ResourceOccurrenceSearchOrderByWithRelationInput.schema';
import { ResourceOccurrenceSearchWhereInputObjectSchema as ResourceOccurrenceSearchWhereInputObjectSchema } from './objects/ResourceOccurrenceSearchWhereInput.schema';
import { ResourceOccurrenceSearchWhereUniqueInputObjectSchema as ResourceOccurrenceSearchWhereUniqueInputObjectSchema } from './objects/ResourceOccurrenceSearchWhereUniqueInput.schema';
import { ResourceOccurrenceSearchCountAggregateInputObjectSchema as ResourceOccurrenceSearchCountAggregateInputObjectSchema } from './objects/ResourceOccurrenceSearchCountAggregateInput.schema';
import { ResourceOccurrenceSearchMinAggregateInputObjectSchema as ResourceOccurrenceSearchMinAggregateInputObjectSchema } from './objects/ResourceOccurrenceSearchMinAggregateInput.schema';
import { ResourceOccurrenceSearchMaxAggregateInputObjectSchema as ResourceOccurrenceSearchMaxAggregateInputObjectSchema } from './objects/ResourceOccurrenceSearchMaxAggregateInput.schema';
import { ResourceOccurrenceSearchAvgAggregateInputObjectSchema as ResourceOccurrenceSearchAvgAggregateInputObjectSchema } from './objects/ResourceOccurrenceSearchAvgAggregateInput.schema';
import { ResourceOccurrenceSearchSumAggregateInputObjectSchema as ResourceOccurrenceSearchSumAggregateInputObjectSchema } from './objects/ResourceOccurrenceSearchSumAggregateInput.schema';

export const ResourceOccurrenceSearchAggregateSchema: z.ZodType<Prisma.ResourceOccurrenceSearchAggregateArgs> = z.object({ orderBy: z.union([ResourceOccurrenceSearchOrderByWithRelationInputObjectSchema, ResourceOccurrenceSearchOrderByWithRelationInputObjectSchema.array()]).optional(), where: ResourceOccurrenceSearchWhereInputObjectSchema.optional(), cursor: ResourceOccurrenceSearchWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ResourceOccurrenceSearchCountAggregateInputObjectSchema ]).optional(), _min: ResourceOccurrenceSearchMinAggregateInputObjectSchema.optional(), _max: ResourceOccurrenceSearchMaxAggregateInputObjectSchema.optional(), _avg: ResourceOccurrenceSearchAvgAggregateInputObjectSchema.optional(), _sum: ResourceOccurrenceSearchSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ResourceOccurrenceSearchAggregateArgs>;

export const ResourceOccurrenceSearchAggregateZodSchema = z.object({ orderBy: z.union([ResourceOccurrenceSearchOrderByWithRelationInputObjectSchema, ResourceOccurrenceSearchOrderByWithRelationInputObjectSchema.array()]).optional(), where: ResourceOccurrenceSearchWhereInputObjectSchema.optional(), cursor: ResourceOccurrenceSearchWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ResourceOccurrenceSearchCountAggregateInputObjectSchema ]).optional(), _min: ResourceOccurrenceSearchMinAggregateInputObjectSchema.optional(), _max: ResourceOccurrenceSearchMaxAggregateInputObjectSchema.optional(), _avg: ResourceOccurrenceSearchAvgAggregateInputObjectSchema.optional(), _sum: ResourceOccurrenceSearchSumAggregateInputObjectSchema.optional() }).strict();