import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { AccountDeletionRequestOrderByWithRelationInputObjectSchema as AccountDeletionRequestOrderByWithRelationInputObjectSchema } from './objects/AccountDeletionRequestOrderByWithRelationInput.schema';
import { AccountDeletionRequestWhereInputObjectSchema as AccountDeletionRequestWhereInputObjectSchema } from './objects/AccountDeletionRequestWhereInput.schema';
import { AccountDeletionRequestWhereUniqueInputObjectSchema as AccountDeletionRequestWhereUniqueInputObjectSchema } from './objects/AccountDeletionRequestWhereUniqueInput.schema';
import { AccountDeletionRequestCountAggregateInputObjectSchema as AccountDeletionRequestCountAggregateInputObjectSchema } from './objects/AccountDeletionRequestCountAggregateInput.schema';
import { AccountDeletionRequestMinAggregateInputObjectSchema as AccountDeletionRequestMinAggregateInputObjectSchema } from './objects/AccountDeletionRequestMinAggregateInput.schema';
import { AccountDeletionRequestMaxAggregateInputObjectSchema as AccountDeletionRequestMaxAggregateInputObjectSchema } from './objects/AccountDeletionRequestMaxAggregateInput.schema';

export const AccountDeletionRequestAggregateSchema: z.ZodType<Prisma.AccountDeletionRequestAggregateArgs> = z.object({ orderBy: z.union([AccountDeletionRequestOrderByWithRelationInputObjectSchema, AccountDeletionRequestOrderByWithRelationInputObjectSchema.array()]).optional(), where: AccountDeletionRequestWhereInputObjectSchema.optional(), cursor: AccountDeletionRequestWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), AccountDeletionRequestCountAggregateInputObjectSchema ]).optional(), _min: AccountDeletionRequestMinAggregateInputObjectSchema.optional(), _max: AccountDeletionRequestMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.AccountDeletionRequestAggregateArgs>;

export const AccountDeletionRequestAggregateZodSchema = z.object({ orderBy: z.union([AccountDeletionRequestOrderByWithRelationInputObjectSchema, AccountDeletionRequestOrderByWithRelationInputObjectSchema.array()]).optional(), where: AccountDeletionRequestWhereInputObjectSchema.optional(), cursor: AccountDeletionRequestWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), AccountDeletionRequestCountAggregateInputObjectSchema ]).optional(), _min: AccountDeletionRequestMinAggregateInputObjectSchema.optional(), _max: AccountDeletionRequestMaxAggregateInputObjectSchema.optional() }).strict();