import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { DeviceAgreementOrderByWithRelationInputObjectSchema as DeviceAgreementOrderByWithRelationInputObjectSchema } from './objects/DeviceAgreementOrderByWithRelationInput.schema';
import { DeviceAgreementWhereInputObjectSchema as DeviceAgreementWhereInputObjectSchema } from './objects/DeviceAgreementWhereInput.schema';
import { DeviceAgreementWhereUniqueInputObjectSchema as DeviceAgreementWhereUniqueInputObjectSchema } from './objects/DeviceAgreementWhereUniqueInput.schema';
import { DeviceAgreementCountAggregateInputObjectSchema as DeviceAgreementCountAggregateInputObjectSchema } from './objects/DeviceAgreementCountAggregateInput.schema';
import { DeviceAgreementMinAggregateInputObjectSchema as DeviceAgreementMinAggregateInputObjectSchema } from './objects/DeviceAgreementMinAggregateInput.schema';
import { DeviceAgreementMaxAggregateInputObjectSchema as DeviceAgreementMaxAggregateInputObjectSchema } from './objects/DeviceAgreementMaxAggregateInput.schema';

export const DeviceAgreementAggregateSchema: z.ZodType<Prisma.DeviceAgreementAggregateArgs> = z.object({ orderBy: z.union([DeviceAgreementOrderByWithRelationInputObjectSchema, DeviceAgreementOrderByWithRelationInputObjectSchema.array()]).optional(), where: DeviceAgreementWhereInputObjectSchema.optional(), cursor: DeviceAgreementWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), DeviceAgreementCountAggregateInputObjectSchema ]).optional(), _min: DeviceAgreementMinAggregateInputObjectSchema.optional(), _max: DeviceAgreementMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.DeviceAgreementAggregateArgs>;

export const DeviceAgreementAggregateZodSchema = z.object({ orderBy: z.union([DeviceAgreementOrderByWithRelationInputObjectSchema, DeviceAgreementOrderByWithRelationInputObjectSchema.array()]).optional(), where: DeviceAgreementWhereInputObjectSchema.optional(), cursor: DeviceAgreementWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), DeviceAgreementCountAggregateInputObjectSchema ]).optional(), _min: DeviceAgreementMinAggregateInputObjectSchema.optional(), _max: DeviceAgreementMaxAggregateInputObjectSchema.optional() }).strict();