import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { PlatformUsageStatsWhereInputObjectSchema as PlatformUsageStatsWhereInputObjectSchema } from './objects/PlatformUsageStatsWhereInput.schema';
import { PlatformUsageStatsOrderByWithAggregationInputObjectSchema as PlatformUsageStatsOrderByWithAggregationInputObjectSchema } from './objects/PlatformUsageStatsOrderByWithAggregationInput.schema';
import { PlatformUsageStatsScalarWhereWithAggregatesInputObjectSchema as PlatformUsageStatsScalarWhereWithAggregatesInputObjectSchema } from './objects/PlatformUsageStatsScalarWhereWithAggregatesInput.schema';
import { PlatformUsageStatsScalarFieldEnumSchema } from './enums/PlatformUsageStatsScalarFieldEnum.schema';
import { PlatformUsageStatsCountAggregateInputObjectSchema as PlatformUsageStatsCountAggregateInputObjectSchema } from './objects/PlatformUsageStatsCountAggregateInput.schema';
import { PlatformUsageStatsMinAggregateInputObjectSchema as PlatformUsageStatsMinAggregateInputObjectSchema } from './objects/PlatformUsageStatsMinAggregateInput.schema';
import { PlatformUsageStatsMaxAggregateInputObjectSchema as PlatformUsageStatsMaxAggregateInputObjectSchema } from './objects/PlatformUsageStatsMaxAggregateInput.schema';
import { PlatformUsageStatsAvgAggregateInputObjectSchema as PlatformUsageStatsAvgAggregateInputObjectSchema } from './objects/PlatformUsageStatsAvgAggregateInput.schema';
import { PlatformUsageStatsSumAggregateInputObjectSchema as PlatformUsageStatsSumAggregateInputObjectSchema } from './objects/PlatformUsageStatsSumAggregateInput.schema';

export const PlatformUsageStatsGroupBySchema: z.ZodType<Prisma.PlatformUsageStatsGroupByArgs> = z.object({ where: PlatformUsageStatsWhereInputObjectSchema.optional(), orderBy: z.union([PlatformUsageStatsOrderByWithAggregationInputObjectSchema, PlatformUsageStatsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: PlatformUsageStatsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(PlatformUsageStatsScalarFieldEnumSchema), _count: z.union([ z.literal(true), PlatformUsageStatsCountAggregateInputObjectSchema ]).optional(), _min: PlatformUsageStatsMinAggregateInputObjectSchema.optional(), _max: PlatformUsageStatsMaxAggregateInputObjectSchema.optional(), _avg: PlatformUsageStatsAvgAggregateInputObjectSchema.optional(), _sum: PlatformUsageStatsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.PlatformUsageStatsGroupByArgs>;

export const PlatformUsageStatsGroupByZodSchema = z.object({ where: PlatformUsageStatsWhereInputObjectSchema.optional(), orderBy: z.union([PlatformUsageStatsOrderByWithAggregationInputObjectSchema, PlatformUsageStatsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: PlatformUsageStatsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(PlatformUsageStatsScalarFieldEnumSchema), _count: z.union([ z.literal(true), PlatformUsageStatsCountAggregateInputObjectSchema ]).optional(), _min: PlatformUsageStatsMinAggregateInputObjectSchema.optional(), _max: PlatformUsageStatsMaxAggregateInputObjectSchema.optional(), _avg: PlatformUsageStatsAvgAggregateInputObjectSchema.optional(), _sum: PlatformUsageStatsSumAggregateInputObjectSchema.optional() }).strict();