import type { Prisma } from '../../../.generated/prisma/client';
import * as z from 'zod';
import { OpportunityApplicationWhereInputObjectSchema as OpportunityApplicationWhereInputObjectSchema } from './objects/OpportunityApplicationWhereInput.schema';
import { OpportunityApplicationOrderByWithAggregationInputObjectSchema as OpportunityApplicationOrderByWithAggregationInputObjectSchema } from './objects/OpportunityApplicationOrderByWithAggregationInput.schema';
import { OpportunityApplicationScalarWhereWithAggregatesInputObjectSchema as OpportunityApplicationScalarWhereWithAggregatesInputObjectSchema } from './objects/OpportunityApplicationScalarWhereWithAggregatesInput.schema';
import { OpportunityApplicationScalarFieldEnumSchema } from './enums/OpportunityApplicationScalarFieldEnum.schema';
import { OpportunityApplicationCountAggregateInputObjectSchema as OpportunityApplicationCountAggregateInputObjectSchema } from './objects/OpportunityApplicationCountAggregateInput.schema';
import { OpportunityApplicationMinAggregateInputObjectSchema as OpportunityApplicationMinAggregateInputObjectSchema } from './objects/OpportunityApplicationMinAggregateInput.schema';
import { OpportunityApplicationMaxAggregateInputObjectSchema as OpportunityApplicationMaxAggregateInputObjectSchema } from './objects/OpportunityApplicationMaxAggregateInput.schema';

export const OpportunityApplicationGroupBySchema: z.ZodType<Prisma.OpportunityApplicationGroupByArgs> = z.object({ where: OpportunityApplicationWhereInputObjectSchema.optional(), orderBy: z.union([OpportunityApplicationOrderByWithAggregationInputObjectSchema, OpportunityApplicationOrderByWithAggregationInputObjectSchema.array()]).optional(), having: OpportunityApplicationScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(OpportunityApplicationScalarFieldEnumSchema), _count: z.union([ z.literal(true), OpportunityApplicationCountAggregateInputObjectSchema ]).optional(), _min: OpportunityApplicationMinAggregateInputObjectSchema.optional(), _max: OpportunityApplicationMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.OpportunityApplicationGroupByArgs>;

export const OpportunityApplicationGroupByZodSchema = z.object({ where: OpportunityApplicationWhereInputObjectSchema.optional(), orderBy: z.union([OpportunityApplicationOrderByWithAggregationInputObjectSchema, OpportunityApplicationOrderByWithAggregationInputObjectSchema.array()]).optional(), having: OpportunityApplicationScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(OpportunityApplicationScalarFieldEnumSchema), _count: z.union([ z.literal(true), OpportunityApplicationCountAggregateInputObjectSchema ]).optional(), _min: OpportunityApplicationMinAggregateInputObjectSchema.optional(), _max: OpportunityApplicationMaxAggregateInputObjectSchema.optional() }).strict();