import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ResourceOccurrenceWhereInputObjectSchema as ResourceOccurrenceWhereInputObjectSchema } from './objects/ResourceOccurrenceWhereInput.schema';
import { ResourceOccurrenceOrderByWithAggregationInputObjectSchema as ResourceOccurrenceOrderByWithAggregationInputObjectSchema } from './objects/ResourceOccurrenceOrderByWithAggregationInput.schema';
import { ResourceOccurrenceScalarWhereWithAggregatesInputObjectSchema as ResourceOccurrenceScalarWhereWithAggregatesInputObjectSchema } from './objects/ResourceOccurrenceScalarWhereWithAggregatesInput.schema';
import { ResourceOccurrenceScalarFieldEnumSchema } from './enums/ResourceOccurrenceScalarFieldEnum.schema';
import { ResourceOccurrenceCountAggregateInputObjectSchema as ResourceOccurrenceCountAggregateInputObjectSchema } from './objects/ResourceOccurrenceCountAggregateInput.schema';
import { ResourceOccurrenceMinAggregateInputObjectSchema as ResourceOccurrenceMinAggregateInputObjectSchema } from './objects/ResourceOccurrenceMinAggregateInput.schema';
import { ResourceOccurrenceMaxAggregateInputObjectSchema as ResourceOccurrenceMaxAggregateInputObjectSchema } from './objects/ResourceOccurrenceMaxAggregateInput.schema';

export const ResourceOccurrenceGroupBySchema: z.ZodType<Prisma.ResourceOccurrenceGroupByArgs> = z.object({ where: ResourceOccurrenceWhereInputObjectSchema.optional(), orderBy: z.union([ResourceOccurrenceOrderByWithAggregationInputObjectSchema, ResourceOccurrenceOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ResourceOccurrenceScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ResourceOccurrenceScalarFieldEnumSchema), _count: z.union([ z.literal(true), ResourceOccurrenceCountAggregateInputObjectSchema ]).optional(), _min: ResourceOccurrenceMinAggregateInputObjectSchema.optional(), _max: ResourceOccurrenceMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ResourceOccurrenceGroupByArgs>;

export const ResourceOccurrenceGroupByZodSchema = z.object({ where: ResourceOccurrenceWhereInputObjectSchema.optional(), orderBy: z.union([ResourceOccurrenceOrderByWithAggregationInputObjectSchema, ResourceOccurrenceOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ResourceOccurrenceScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ResourceOccurrenceScalarFieldEnumSchema), _count: z.union([ z.literal(true), ResourceOccurrenceCountAggregateInputObjectSchema ]).optional(), _min: ResourceOccurrenceMinAggregateInputObjectSchema.optional(), _max: ResourceOccurrenceMaxAggregateInputObjectSchema.optional() }).strict();