import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ResourceOccurrenceSearchWhereInputObjectSchema as ResourceOccurrenceSearchWhereInputObjectSchema } from './objects/ResourceOccurrenceSearchWhereInput.schema';
import { ResourceOccurrenceSearchOrderByWithAggregationInputObjectSchema as ResourceOccurrenceSearchOrderByWithAggregationInputObjectSchema } from './objects/ResourceOccurrenceSearchOrderByWithAggregationInput.schema';
import { ResourceOccurrenceSearchScalarWhereWithAggregatesInputObjectSchema as ResourceOccurrenceSearchScalarWhereWithAggregatesInputObjectSchema } from './objects/ResourceOccurrenceSearchScalarWhereWithAggregatesInput.schema';
import { ResourceOccurrenceSearchScalarFieldEnumSchema } from './enums/ResourceOccurrenceSearchScalarFieldEnum.schema';
import { ResourceOccurrenceSearchCountAggregateInputObjectSchema as ResourceOccurrenceSearchCountAggregateInputObjectSchema } from './objects/ResourceOccurrenceSearchCountAggregateInput.schema';
import { ResourceOccurrenceSearchMinAggregateInputObjectSchema as ResourceOccurrenceSearchMinAggregateInputObjectSchema } from './objects/ResourceOccurrenceSearchMinAggregateInput.schema';
import { ResourceOccurrenceSearchMaxAggregateInputObjectSchema as ResourceOccurrenceSearchMaxAggregateInputObjectSchema } from './objects/ResourceOccurrenceSearchMaxAggregateInput.schema';
import { ResourceOccurrenceSearchAvgAggregateInputObjectSchema as ResourceOccurrenceSearchAvgAggregateInputObjectSchema } from './objects/ResourceOccurrenceSearchAvgAggregateInput.schema';
import { ResourceOccurrenceSearchSumAggregateInputObjectSchema as ResourceOccurrenceSearchSumAggregateInputObjectSchema } from './objects/ResourceOccurrenceSearchSumAggregateInput.schema';

export const ResourceOccurrenceSearchGroupBySchema: z.ZodType<Prisma.ResourceOccurrenceSearchGroupByArgs> = z.object({ where: ResourceOccurrenceSearchWhereInputObjectSchema.optional(), orderBy: z.union([ResourceOccurrenceSearchOrderByWithAggregationInputObjectSchema, ResourceOccurrenceSearchOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ResourceOccurrenceSearchScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ResourceOccurrenceSearchScalarFieldEnumSchema), _count: z.union([ z.literal(true), ResourceOccurrenceSearchCountAggregateInputObjectSchema ]).optional(), _min: ResourceOccurrenceSearchMinAggregateInputObjectSchema.optional(), _max: ResourceOccurrenceSearchMaxAggregateInputObjectSchema.optional(), _avg: ResourceOccurrenceSearchAvgAggregateInputObjectSchema.optional(), _sum: ResourceOccurrenceSearchSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ResourceOccurrenceSearchGroupByArgs>;

export const ResourceOccurrenceSearchGroupByZodSchema = z.object({ where: ResourceOccurrenceSearchWhereInputObjectSchema.optional(), orderBy: z.union([ResourceOccurrenceSearchOrderByWithAggregationInputObjectSchema, ResourceOccurrenceSearchOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ResourceOccurrenceSearchScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ResourceOccurrenceSearchScalarFieldEnumSchema), _count: z.union([ z.literal(true), ResourceOccurrenceSearchCountAggregateInputObjectSchema ]).optional(), _min: ResourceOccurrenceSearchMinAggregateInputObjectSchema.optional(), _max: ResourceOccurrenceSearchMaxAggregateInputObjectSchema.optional(), _avg: ResourceOccurrenceSearchAvgAggregateInputObjectSchema.optional(), _sum: ResourceOccurrenceSearchSumAggregateInputObjectSchema.optional() }).strict();