import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ScannableDocumentMealHitWhereInputObjectSchema as ScannableDocumentMealHitWhereInputObjectSchema } from './objects/ScannableDocumentMealHitWhereInput.schema';
import { ScannableDocumentMealHitOrderByWithAggregationInputObjectSchema as ScannableDocumentMealHitOrderByWithAggregationInputObjectSchema } from './objects/ScannableDocumentMealHitOrderByWithAggregationInput.schema';
import { ScannableDocumentMealHitScalarWhereWithAggregatesInputObjectSchema as ScannableDocumentMealHitScalarWhereWithAggregatesInputObjectSchema } from './objects/ScannableDocumentMealHitScalarWhereWithAggregatesInput.schema';
import { ScannableDocumentMealHitScalarFieldEnumSchema } from './enums/ScannableDocumentMealHitScalarFieldEnum.schema';
import { ScannableDocumentMealHitCountAggregateInputObjectSchema as ScannableDocumentMealHitCountAggregateInputObjectSchema } from './objects/ScannableDocumentMealHitCountAggregateInput.schema';
import { ScannableDocumentMealHitMinAggregateInputObjectSchema as ScannableDocumentMealHitMinAggregateInputObjectSchema } from './objects/ScannableDocumentMealHitMinAggregateInput.schema';
import { ScannableDocumentMealHitMaxAggregateInputObjectSchema as ScannableDocumentMealHitMaxAggregateInputObjectSchema } from './objects/ScannableDocumentMealHitMaxAggregateInput.schema';

export const ScannableDocumentMealHitGroupBySchema: z.ZodType<Prisma.ScannableDocumentMealHitGroupByArgs> = z.object({ where: ScannableDocumentMealHitWhereInputObjectSchema.optional(), orderBy: z.union([ScannableDocumentMealHitOrderByWithAggregationInputObjectSchema, ScannableDocumentMealHitOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ScannableDocumentMealHitScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ScannableDocumentMealHitScalarFieldEnumSchema), _count: z.union([ z.literal(true), ScannableDocumentMealHitCountAggregateInputObjectSchema ]).optional(), _min: ScannableDocumentMealHitMinAggregateInputObjectSchema.optional(), _max: ScannableDocumentMealHitMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ScannableDocumentMealHitGroupByArgs>;

export const ScannableDocumentMealHitGroupByZodSchema = z.object({ where: ScannableDocumentMealHitWhereInputObjectSchema.optional(), orderBy: z.union([ScannableDocumentMealHitOrderByWithAggregationInputObjectSchema, ScannableDocumentMealHitOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ScannableDocumentMealHitScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ScannableDocumentMealHitScalarFieldEnumSchema), _count: z.union([ z.literal(true), ScannableDocumentMealHitCountAggregateInputObjectSchema ]).optional(), _min: ScannableDocumentMealHitMinAggregateInputObjectSchema.optional(), _max: ScannableDocumentMealHitMaxAggregateInputObjectSchema.optional() }).strict();