import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { AccountDeletionRequestWhereInputObjectSchema as AccountDeletionRequestWhereInputObjectSchema } from './objects/AccountDeletionRequestWhereInput.schema';
import { AccountDeletionRequestOrderByWithAggregationInputObjectSchema as AccountDeletionRequestOrderByWithAggregationInputObjectSchema } from './objects/AccountDeletionRequestOrderByWithAggregationInput.schema';
import { AccountDeletionRequestScalarWhereWithAggregatesInputObjectSchema as AccountDeletionRequestScalarWhereWithAggregatesInputObjectSchema } from './objects/AccountDeletionRequestScalarWhereWithAggregatesInput.schema';
import { AccountDeletionRequestScalarFieldEnumSchema } from './enums/AccountDeletionRequestScalarFieldEnum.schema';
import { AccountDeletionRequestCountAggregateInputObjectSchema as AccountDeletionRequestCountAggregateInputObjectSchema } from './objects/AccountDeletionRequestCountAggregateInput.schema';
import { AccountDeletionRequestMinAggregateInputObjectSchema as AccountDeletionRequestMinAggregateInputObjectSchema } from './objects/AccountDeletionRequestMinAggregateInput.schema';
import { AccountDeletionRequestMaxAggregateInputObjectSchema as AccountDeletionRequestMaxAggregateInputObjectSchema } from './objects/AccountDeletionRequestMaxAggregateInput.schema';

export const AccountDeletionRequestGroupBySchema: z.ZodType<Prisma.AccountDeletionRequestGroupByArgs> = z.object({ where: AccountDeletionRequestWhereInputObjectSchema.optional(), orderBy: z.union([AccountDeletionRequestOrderByWithAggregationInputObjectSchema, AccountDeletionRequestOrderByWithAggregationInputObjectSchema.array()]).optional(), having: AccountDeletionRequestScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(AccountDeletionRequestScalarFieldEnumSchema), _count: z.union([ z.literal(true), AccountDeletionRequestCountAggregateInputObjectSchema ]).optional(), _min: AccountDeletionRequestMinAggregateInputObjectSchema.optional(), _max: AccountDeletionRequestMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.AccountDeletionRequestGroupByArgs>;

export const AccountDeletionRequestGroupByZodSchema = z.object({ where: AccountDeletionRequestWhereInputObjectSchema.optional(), orderBy: z.union([AccountDeletionRequestOrderByWithAggregationInputObjectSchema, AccountDeletionRequestOrderByWithAggregationInputObjectSchema.array()]).optional(), having: AccountDeletionRequestScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(AccountDeletionRequestScalarFieldEnumSchema), _count: z.union([ z.literal(true), AccountDeletionRequestCountAggregateInputObjectSchema ]).optional(), _min: AccountDeletionRequestMinAggregateInputObjectSchema.optional(), _max: AccountDeletionRequestMaxAggregateInputObjectSchema.optional() }).strict();