import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ResourceInteractionWhereInputObjectSchema as ResourceInteractionWhereInputObjectSchema } from './objects/ResourceInteractionWhereInput.schema';
import { ResourceInteractionOrderByWithAggregationInputObjectSchema as ResourceInteractionOrderByWithAggregationInputObjectSchema } from './objects/ResourceInteractionOrderByWithAggregationInput.schema';
import { ResourceInteractionScalarWhereWithAggregatesInputObjectSchema as ResourceInteractionScalarWhereWithAggregatesInputObjectSchema } from './objects/ResourceInteractionScalarWhereWithAggregatesInput.schema';
import { ResourceInteractionScalarFieldEnumSchema } from './enums/ResourceInteractionScalarFieldEnum.schema';
import { ResourceInteractionCountAggregateInputObjectSchema as ResourceInteractionCountAggregateInputObjectSchema } from './objects/ResourceInteractionCountAggregateInput.schema';
import { ResourceInteractionMinAggregateInputObjectSchema as ResourceInteractionMinAggregateInputObjectSchema } from './objects/ResourceInteractionMinAggregateInput.schema';
import { ResourceInteractionMaxAggregateInputObjectSchema as ResourceInteractionMaxAggregateInputObjectSchema } from './objects/ResourceInteractionMaxAggregateInput.schema';

export const ResourceInteractionGroupBySchema: z.ZodType<Prisma.ResourceInteractionGroupByArgs> = z.object({ where: ResourceInteractionWhereInputObjectSchema.optional(), orderBy: z.union([ResourceInteractionOrderByWithAggregationInputObjectSchema, ResourceInteractionOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ResourceInteractionScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ResourceInteractionScalarFieldEnumSchema), _count: z.union([ z.literal(true), ResourceInteractionCountAggregateInputObjectSchema ]).optional(), _min: ResourceInteractionMinAggregateInputObjectSchema.optional(), _max: ResourceInteractionMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ResourceInteractionGroupByArgs>;

export const ResourceInteractionGroupByZodSchema = z.object({ where: ResourceInteractionWhereInputObjectSchema.optional(), orderBy: z.union([ResourceInteractionOrderByWithAggregationInputObjectSchema, ResourceInteractionOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ResourceInteractionScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ResourceInteractionScalarFieldEnumSchema), _count: z.union([ z.literal(true), ResourceInteractionCountAggregateInputObjectSchema ]).optional(), _min: ResourceInteractionMinAggregateInputObjectSchema.optional(), _max: ResourceInteractionMaxAggregateInputObjectSchema.optional() }).strict();