import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { MealOccurrenceSearchWhereInputObjectSchema as MealOccurrenceSearchWhereInputObjectSchema } from './objects/MealOccurrenceSearchWhereInput.schema';
import { MealOccurrenceSearchOrderByWithAggregationInputObjectSchema as MealOccurrenceSearchOrderByWithAggregationInputObjectSchema } from './objects/MealOccurrenceSearchOrderByWithAggregationInput.schema';
import { MealOccurrenceSearchScalarWhereWithAggregatesInputObjectSchema as MealOccurrenceSearchScalarWhereWithAggregatesInputObjectSchema } from './objects/MealOccurrenceSearchScalarWhereWithAggregatesInput.schema';
import { MealOccurrenceSearchScalarFieldEnumSchema } from './enums/MealOccurrenceSearchScalarFieldEnum.schema';
import { MealOccurrenceSearchCountAggregateInputObjectSchema as MealOccurrenceSearchCountAggregateInputObjectSchema } from './objects/MealOccurrenceSearchCountAggregateInput.schema';
import { MealOccurrenceSearchMinAggregateInputObjectSchema as MealOccurrenceSearchMinAggregateInputObjectSchema } from './objects/MealOccurrenceSearchMinAggregateInput.schema';
import { MealOccurrenceSearchMaxAggregateInputObjectSchema as MealOccurrenceSearchMaxAggregateInputObjectSchema } from './objects/MealOccurrenceSearchMaxAggregateInput.schema';
import { MealOccurrenceSearchAvgAggregateInputObjectSchema as MealOccurrenceSearchAvgAggregateInputObjectSchema } from './objects/MealOccurrenceSearchAvgAggregateInput.schema';
import { MealOccurrenceSearchSumAggregateInputObjectSchema as MealOccurrenceSearchSumAggregateInputObjectSchema } from './objects/MealOccurrenceSearchSumAggregateInput.schema';

export const MealOccurrenceSearchGroupBySchema: z.ZodType<Prisma.MealOccurrenceSearchGroupByArgs> = z.object({ where: MealOccurrenceSearchWhereInputObjectSchema.optional(), orderBy: z.union([MealOccurrenceSearchOrderByWithAggregationInputObjectSchema, MealOccurrenceSearchOrderByWithAggregationInputObjectSchema.array()]).optional(), having: MealOccurrenceSearchScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(MealOccurrenceSearchScalarFieldEnumSchema), _count: z.union([ z.literal(true), MealOccurrenceSearchCountAggregateInputObjectSchema ]).optional(), _min: MealOccurrenceSearchMinAggregateInputObjectSchema.optional(), _max: MealOccurrenceSearchMaxAggregateInputObjectSchema.optional(), _avg: MealOccurrenceSearchAvgAggregateInputObjectSchema.optional(), _sum: MealOccurrenceSearchSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.MealOccurrenceSearchGroupByArgs>;

export const MealOccurrenceSearchGroupByZodSchema = z.object({ where: MealOccurrenceSearchWhereInputObjectSchema.optional(), orderBy: z.union([MealOccurrenceSearchOrderByWithAggregationInputObjectSchema, MealOccurrenceSearchOrderByWithAggregationInputObjectSchema.array()]).optional(), having: MealOccurrenceSearchScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(MealOccurrenceSearchScalarFieldEnumSchema), _count: z.union([ z.literal(true), MealOccurrenceSearchCountAggregateInputObjectSchema ]).optional(), _min: MealOccurrenceSearchMinAggregateInputObjectSchema.optional(), _max: MealOccurrenceSearchMaxAggregateInputObjectSchema.optional(), _avg: MealOccurrenceSearchAvgAggregateInputObjectSchema.optional(), _sum: MealOccurrenceSearchSumAggregateInputObjectSchema.optional() }).strict();