import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ResourceOccurrenceSearchSelectObjectSchema as ResourceOccurrenceSearchSelectObjectSchema } from './objects/ResourceOccurrenceSearchSelect.schema';
import { ResourceOccurrenceSearchIncludeObjectSchema as ResourceOccurrenceSearchIncludeObjectSchema } from './objects/ResourceOccurrenceSearchInclude.schema';
import { ResourceOccurrenceSearchWhereUniqueInputObjectSchema as ResourceOccurrenceSearchWhereUniqueInputObjectSchema } from './objects/ResourceOccurrenceSearchWhereUniqueInput.schema';
import { ResourceOccurrenceSearchCreateInputObjectSchema as ResourceOccurrenceSearchCreateInputObjectSchema } from './objects/ResourceOccurrenceSearchCreateInput.schema';
import { ResourceOccurrenceSearchUncheckedCreateInputObjectSchema as ResourceOccurrenceSearchUncheckedCreateInputObjectSchema } from './objects/ResourceOccurrenceSearchUncheckedCreateInput.schema';
import { ResourceOccurrenceSearchUpdateInputObjectSchema as ResourceOccurrenceSearchUpdateInputObjectSchema } from './objects/ResourceOccurrenceSearchUpdateInput.schema';
import { ResourceOccurrenceSearchUncheckedUpdateInputObjectSchema as ResourceOccurrenceSearchUncheckedUpdateInputObjectSchema } from './objects/ResourceOccurrenceSearchUncheckedUpdateInput.schema';

export const ResourceOccurrenceSearchUpsertOneSchema: z.ZodType<Prisma.ResourceOccurrenceSearchUpsertArgs> = z.object({ select: ResourceOccurrenceSearchSelectObjectSchema.optional(), include: ResourceOccurrenceSearchIncludeObjectSchema.optional(), where: ResourceOccurrenceSearchWhereUniqueInputObjectSchema, create: z.union([ ResourceOccurrenceSearchCreateInputObjectSchema, ResourceOccurrenceSearchUncheckedCreateInputObjectSchema ]), update: z.union([ ResourceOccurrenceSearchUpdateInputObjectSchema, ResourceOccurrenceSearchUncheckedUpdateInputObjectSchema ]) }).strict() as unknown as z.ZodType<Prisma.ResourceOccurrenceSearchUpsertArgs>;

export const ResourceOccurrenceSearchUpsertOneZodSchema = z.object({ select: ResourceOccurrenceSearchSelectObjectSchema.optional(), include: ResourceOccurrenceSearchIncludeObjectSchema.optional(), where: ResourceOccurrenceSearchWhereUniqueInputObjectSchema, create: z.union([ ResourceOccurrenceSearchCreateInputObjectSchema, ResourceOccurrenceSearchUncheckedCreateInputObjectSchema ]), update: z.union([ ResourceOccurrenceSearchUpdateInputObjectSchema, ResourceOccurrenceSearchUncheckedUpdateInputObjectSchema ]) }).strict();