import * as z from 'zod';
import type { Prisma } from '@prisma/client';
import { ScannableDocumentCreateWithoutScannable_document_meal_hitsInputObjectSchema as ScannableDocumentCreateWithoutScannable_document_meal_hitsInputObjectSchema } from './ScannableDocumentCreateWithoutScannable_document_meal_hitsInput.schema';
import { ScannableDocumentUncheckedCreateWithoutScannable_document_meal_hitsInputObjectSchema as ScannableDocumentUncheckedCreateWithoutScannable_document_meal_hitsInputObjectSchema } from './ScannableDocumentUncheckedCreateWithoutScannable_document_meal_hitsInput.schema';
import { ScannableDocumentCreateOrConnectWithoutScannable_document_meal_hitsInputObjectSchema as ScannableDocumentCreateOrConnectWithoutScannable_document_meal_hitsInputObjectSchema } from './ScannableDocumentCreateOrConnectWithoutScannable_document_meal_hitsInput.schema';
import { ScannableDocumentUpsertWithoutScannable_document_meal_hitsInputObjectSchema as ScannableDocumentUpsertWithoutScannable_document_meal_hitsInputObjectSchema } from './ScannableDocumentUpsertWithoutScannable_document_meal_hitsInput.schema';
import { ScannableDocumentWhereUniqueInputObjectSchema as ScannableDocumentWhereUniqueInputObjectSchema } from './ScannableDocumentWhereUniqueInput.schema';
import { ScannableDocumentUpdateToOneWithWhereWithoutScannable_document_meal_hitsInputObjectSchema as ScannableDocumentUpdateToOneWithWhereWithoutScannable_document_meal_hitsInputObjectSchema } from './ScannableDocumentUpdateToOneWithWhereWithoutScannable_document_meal_hitsInput.schema';
import { ScannableDocumentUpdateWithoutScannable_document_meal_hitsInputObjectSchema as ScannableDocumentUpdateWithoutScannable_document_meal_hitsInputObjectSchema } from './ScannableDocumentUpdateWithoutScannable_document_meal_hitsInput.schema';
import { ScannableDocumentUncheckedUpdateWithoutScannable_document_meal_hitsInputObjectSchema as ScannableDocumentUncheckedUpdateWithoutScannable_document_meal_hitsInputObjectSchema } from './ScannableDocumentUncheckedUpdateWithoutScannable_document_meal_hitsInput.schema'

const makeSchema = () => z.object({
  create: z.union([z.lazy(() => ScannableDocumentCreateWithoutScannable_document_meal_hitsInputObjectSchema), z.lazy(() => ScannableDocumentUncheckedCreateWithoutScannable_document_meal_hitsInputObjectSchema)]).optional(),
  connectOrCreate: z.lazy(() => ScannableDocumentCreateOrConnectWithoutScannable_document_meal_hitsInputObjectSchema).optional(),
  upsert: z.lazy(() => ScannableDocumentUpsertWithoutScannable_document_meal_hitsInputObjectSchema).optional(),
  connect: z.lazy(() => ScannableDocumentWhereUniqueInputObjectSchema).optional(),
  update: z.union([z.lazy(() => ScannableDocumentUpdateToOneWithWhereWithoutScannable_document_meal_hitsInputObjectSchema), z.lazy(() => ScannableDocumentUpdateWithoutScannable_document_meal_hitsInputObjectSchema), z.lazy(() => ScannableDocumentUncheckedUpdateWithoutScannable_document_meal_hitsInputObjectSchema)]).optional()
}).strict();
export const ScannableDocumentUpdateOneRequiredWithoutScannable_document_meal_hitsNestedInputObjectSchema: z.ZodType<Prisma.ScannableDocumentUpdateOneRequiredWithoutScannable_document_meal_hitsNestedInput> = makeSchema() as unknown as z.ZodType<Prisma.ScannableDocumentUpdateOneRequiredWithoutScannable_document_meal_hitsNestedInput>;
export const ScannableDocumentUpdateOneRequiredWithoutScannable_document_meal_hitsNestedInputObjectZodSchema = makeSchema();
